### PR TITLE
Kibi 1155

### PR DESCRIPTION
**Pull request by ankghosh-groupon**
@alena Please review

### CODE REVIEW

**Comment by pierre** [comment]
@ankghosh-groupon Make sure to use `backport-0.18.x` as a base branch, `master` is not compatible with the version of Kill Bill you are running.

**Comment by ankghosh-groupon** [comment]
@pierre 
cc @alena merge coflicts resolved

**Comment by pierre** [comment]
@ankghosh-groupon: Alena's handle is @alenad.

@alenad: could you review the changes? Whenever it's ready to be merged, let me know, and I'll do the release.

**Review by alenad — APPROVED** [review]

**Comment by alenad** [comment]
@pierre changes reviewed, ready to be merged and released

**Comment by pierre** [comment]
v0.1.17 has been released.

**Pull request merged**
